### PR TITLE
Scripts for applying / patching averaging kernels

### PR DESCRIPTION
**Pull request by bjornlindr**
For applying averaging kernels on MATS/HIAMCM data.

### CODE REVIEW

**Comment by bjornlindr** [comment]
I see now that there is some logs that were for debugging / improving runtime. 
Could remove to not litter the repo.

**Comment by OleMartinChristensen** [comment]
please do

**Comment by bjornlindr** [comment]
Now removed the logs.

**Review by OleMartinChristensen — APPROVED** [review]
looks good

**Pull request merged**
